Repository nimblehq/shorten-link-mac, pull requests merged in 2021-11, with the labels that each got.

#24 [#1] Init project
  .gitignore
  Podfile
  Podfile.lock
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ShortenLink.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ShortenLink.xcworkspace/contents.xcworkspacedata
  ShortenLink.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Application/Base.lproj/Main.storyboard
  ShortenLink/Application/Info.plist
  ShortenLink/Application/ShortenLink.entitlements
  ShortenLink/Assets.xcassets/AccentColor.colorset/Contents.json
  ShortenLink/Assets.xcassets/AppIcon.appiconset/Contents.json
  ShortenLink/Assets.xcassets/Contents.json
  ShortenLink/Scenes/Home/ViewController.swift
  ShortenLinkTests/Info.plist
  ShortenLinkTests/ShortenLinkTests.swift
  ShortenLinkUITests/Info.plist
  ShortenLinkUITests/ShortenLinkUITests.swift
Labels: type : chore

#26 [#4] [UI] As a user, I can make a shortened link
  .gitignore
  Podfile
  Podfile.lock
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Application/Base.lproj/Main.storyboard
  ShortenLink/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ShortenLink/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ShortenLink/Resources/Assets.xcassets/Contents.json
  ShortenLink/Resources/Assets.xcassets/clear.imageset/Contents.json
  ShortenLink/Resources/Assets.xcassets/clear.imageset/Icon - Clear.pdf
  ShortenLink/Resources/Localize/en.lproj/Localizable.strings
  ShortenLink/Scenes/ShortenLink/ShortenLinkViewController.swift
  ShortenLink/Views/ClearableTextField.swift
  swiftgen.yml
Labels: type : feature

#27 [#2][#3] UI and Integrate icon in status bar
  Podfile
  Podfile.lock
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Resources/Assets.xcassets/setting_ic.imageset/Contents.json
  ShortenLink/Resources/Assets.xcassets/setting_ic.imageset/setting_ic.pdf
  ShortenLink/Resources/Assets.xcassets/status_bar_icon.imageset/Contents.json
  ShortenLink/Resources/Assets.xcassets/status_bar_icon.imageset/status_bar_icon.pdf
  ShortenLink/Resources/Localize/en.lproj/Localizable.strings
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewController.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewModel.swift
  ShortenLink/Supports/Extensions/NSView+AddSubViews.swift
Labels: type : feature

#28 [#25] [Chore] Set Up Network Layer
  .github/PULL_REQUEST_TEMPLATE.md
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Data/NetworkAPI/Core/NetworkAPIError.swift
  ShortenLink/Data/NetworkAPI/Core/NetworkAPIProtocol.swift
  ShortenLink/Data/NetworkAPI/Core/RequestConfiguration.swift
  ShortenLink/Data/NetworkAPI/Interceptors/.gitkeep
  ShortenLink/Data/NetworkAPI/Models/.gitkeep
  ShortenLink/Data/NetworkAPI/NetworkAPI.swift
  ShortenLink/Data/NetworkAPI/RequestConfigurations/.gitkeep
  ShortenLink/Data/Repositories/.gitkeep
Labels: type : chore

#29 [#6] [Backend] Add network layer files and add ShortenLinkUseCase
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Application/ShortenLink.entitlements
  ShortenLink/Data/NetworkAPI/Core/APIRequestConfiguration.swift
  ShortenLink/Data/NetworkAPI/Models/APIShortenLink.swift
  ShortenLink/Data/NetworkAPI/NetworkAPI.swift
  ShortenLink/Data/NetworkAPI/RequestConfigurations/LinksRequestConfiguration.swift
  ShortenLink/Data/Repositories/CreateShortenLink/CreateShortenLinkRepository.swift
  ShortenLink/Domain/Entities/ShortenLink.swift
  ShortenLink/Domain/Interfaces/Repositories/CreateShortenLinkRepositoryProtocol.swift
  ShortenLink/Domain/UseCases/CreateShortenLink/CreateShortenLinkUseCase.swift
  ShortenLink/Supports/Extensions/Foundation/DateFormatter/DateFormatter+Formats.swift
  ShortenLink/Supports/Extensions/Foundation/JSONDecoder+Default/JSONDecoder+Default.swift
  ShortenLink/Supports/Extensions/Foundation/String/String+Date.swift
Labels: type : feature, epic: application

#31 [30] [Backend] As a user, I can sign-in with my google account
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Application/Info.plist
  ShortenLink/Constants/Constants.swift
  ShortenLink/Data/Keychain/Keychain.swift
  ShortenLink/Data/Keychain/KeychainKey.swift
  ShortenLink/Data/Keychain/Models/KeychainUser.swift
  ShortenLink/Data/NetworkAPI/Models/APIUser.swift
  ShortenLink/Data/NetworkAPI/NetworkAPI.swift
  ShortenLink/Data/NetworkAPI/RequestConfigurations/UserRequestConfiguration.swift
  ShortenLink/Data/Repositories/User/LoginRepository.swift
  ShortenLink/Data/Repositories/User/UserSessionRepository.swift
  ShortenLink/Domain/Entities/User.swift
  ShortenLink/Domain/Factories/DependencyFactory.swift
  ShortenLink/Domain/Interfaces/Repositories/LoginRepositoryProtocol.swift
  ShortenLink/Domain/Interfaces/Repositories/UserSessionRepositoryProtocol.swift
  ShortenLink/Domain/UseCases/User/UserUseCase.swift
Labels: type : feature

#32 [#7] [UI] List of shorten links
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Models/ShortenLink.swift
  ShortenLink/Resources/Assets.xcassets/delete_ic.imageset/Contents.json
  ShortenLink/Resources/Assets.xcassets/delete_ic.imageset/delete_ic.pdf
  ShortenLink/Resources/Assets.xcassets/edit_ic.imageset/Contents.json
  ShortenLink/Resources/Assets.xcassets/edit_ic.imageset/edit_ic.pdf
  ShortenLink/Resources/Localize/en.lproj/Localizable.strings
  ShortenLink/Scenes/LinksPopOver/Cell/ShortenLinkCellView.swift
  ShortenLink/Scenes/LinksPopOver/Cell/ShortenLinkCellViewModel.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewController.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewModel.swift
  ShortenLink/Supports/Extensions/Foundation/Date/Date+MakeCreatedAtText.swift
  ShortenLink/Supports/Helpers/EventMonitor.swift
  ShortenLink/Views/CustomTableRowView.swift
Labels: type : feature

#34 [#5] [Integrate] As a user, I can make a shortened link
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink.xcodeproj/xcshareddata/xcschemes/ShortenLink.xcscheme
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Application/Base.lproj/Main.storyboard
  ShortenLink/Data/NetworkAPI/RequestConfigurations/LinksRequestConfiguration.swift
  ShortenLink/Data/Repositories/ShortenedLink/ShortenedLinkRepository.swift
  ShortenLink/Domain/Factories/DependencyFactory+UseCaseFactoryProtocol.swift
  ShortenLink/Domain/Factories/DependencyFactory+ViewModelFactoryProtocol.swift
  ShortenLink/Domain/Factories/DependencyFactory.swift
  ShortenLink/Domain/Interfaces/Repositories/ShortenedLink/ShortenedLinkRepositoryProtocol.swift
  ShortenLink/Domain/UseCases/ShortenedLink/CreateShortenLinkUseCase.swift
  ShortenLink/Factories/Data/RepositoryFactoryProtocol.swift
  ShortenLink/Factories/Domain/UseCaseFactoryProtocol.swift
  ShortenLink/Factories/Presentation/ViewModelFactoryProtocol.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewController.swift
  ShortenLink/Scenes/ShortenLink/ShortenLinkViewController.swift
  ShortenLink/Scenes/ShortenLink/ShortenLinkViewModel.swift
  ShortenLink/Supports/Extensions/AppKit/NSPasteboard/NSPasteboard+SetGeneralString.swift
Labels: type : feature

#35 [#18] [Integrate] As a user, I can use shortcut key to create a shortened link
  Podfile
  Podfile.lock
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Domain/Factories/DependencyFactory.swift
  ShortenLink/Factories/Application/DependencyFactory+UseCaseFactoryProtocol.swift
  ShortenLink/Factories/Application/DependencyFactory+ViewModelFactoryProtocol.swift
  ShortenLink/Factories/Application/DependencyFactory.swift
  ShortenLink/Resources/Localize/en.lproj/Localizable.strings
  ShortenLink/Scenes/ShortenLink/ShortenLinkViewController.swift
  ShortenLink/Scenes/ShortenLink/ShortenLinkViewModel.swift
  ShortenLink/Supports/Extensions/AppKit/NSPasteboard/NSPasteboard+ReadString.swift
  ShortenLink/Supports/Extensions/Toast.swift
Labels: type : feature

#38 [#15] [UI] As a user, I can delete a shortened link
  ShortenLink/Resources/Localize/en.lproj/Localizable.strings
  ShortenLink/Scenes/LinksPopOver/Cell/ShortenLinkCellView.swift
Labels: type : feature

#36 [22] [Integrate] As a user, I can sign-in with my google account
  Podfile
  Podfile.lock
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Application/Info.plist
  ShortenLink/Domain/Factories/DependencyFactory+UseCaseFactoryProtocol.swift
  ShortenLink/Domain/Factories/DependencyFactory.swift
  ShortenLink/Domain/UseCases/GoogleSignIn/GSignInUseCase.swift
  ShortenLink/Domain/UseCases/User/UserUseCase.swift
  ShortenLink/Factories/Data/RepositoryFactoryProtocol.swift
  ShortenLink/Factories/Domain/UseCaseFactoryProtocol.swift
Labels: type : feature

#46 [#41] [UI] [Integrate] As a User, I can see More options on bottom right
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Resources/Assets.xcassets/About.imageset/About.pdf
  ShortenLink/Resources/Assets.xcassets/About.imageset/Contents.json
  ShortenLink/Resources/Assets.xcassets/More.imageset/Contents.json
  ShortenLink/Resources/Assets.xcassets/More.imageset/More.pdf
  ShortenLink/Resources/Localize/en.lproj/Localizable.strings
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewController.swift
  ShortenLink/Scenes/MoreOption/MoreOptionViewController.swift
  ShortenLink/Supports/Extensions/AppKit/NSButton/NSButton+ImageOnly.swift
Labels: type : feature

#45 [42] [Backend] As a User, I can sign out my account
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Data/Keychain/KeychainKey.swift
  ShortenLink/Data/NetworkAPI/RequestConfigurations/UserRequestConfiguration.swift
  ShortenLink/Data/Repositories/User/LogOutRepository.swift
  ShortenLink/Data/Repositories/User/LoginRepository.swift
  ShortenLink/Data/Repositories/User/UserSessionRepository.swift
  ShortenLink/Domain/Factories/DependencyFactory+UseCaseFactoryProtocol.swift
  ShortenLink/Domain/Factories/DependencyFactory.swift
  ShortenLink/Domain/Interfaces/Repositories/User/LogOutRepositoryProtocol.swift
  ShortenLink/Domain/Interfaces/Repositories/User/UserSessionRepositoryProtocol.swift
  ShortenLink/Domain/UseCases/User/UserUseCase.swift
  ShortenLink/Factories/Data/RepositoryFactoryProtocol.swift
Labels: type : feature

#40 [#21] UI sign in with google
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Domain/Factories/DependencyFactory+ViewModelFactoryProtocol.swift
  ShortenLink/Factories/Presentation/ViewModelFactoryProtocol.swift
  ShortenLink/Resources/Assets.xcassets/google_ic.imageset/Contents.json
  ShortenLink/Resources/Assets.xcassets/google_ic.imageset/google_ic.pdf
  ShortenLink/Resources/Localize/en.lproj/Localizable.strings
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewController.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewModel.swift
  ShortenLink/Scenes/Login/LoginViewController.swift
  ShortenLink/Scenes/Login/LoginViewModel.swift
  ShortenLink/Scenes/MoreOption/MoreOptionViewController.swift
Labels: type : feature

#47 [44] [Integrate] As a User, I can quit the menu bar app
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Scenes/MoreOption/MoreOptionViewController.swift
Labels: type : feature

#48 [43] [Integrate] As a User, I can sign out my account
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewController.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewModel.swift
  ShortenLink/Scenes/MoreOption/MoreOptionViewController.swift
Labels: type : feature

#49 [#8] [Integrate] As a user, I can see list of shortened link
  ShortenLink/Domain/Factories/DependencyFactory+ViewModelFactoryProtocol.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewController.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewModel.swift
Labels: type : feature

#39 [#12] [Integrate] As a user, I can delete a shortened link
  ShortenLink/Domain/Factories/DependencyFactory+ViewModelFactoryProtocol.swift
  ShortenLink/Scenes/LinksPopOver/Cell/ShortenLinkCellViewModel.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewModel.swift
  ShortenLink/Scenes/ShortenLink/ShortenLinkViewController.swift
Labels: type : feature

#52 [#51] Update build script
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink.xcodeproj/xcshareddata/xcschemes/ShortenLink.xcscheme
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Domain/UseCases/User/UserUseCase.swift
  ShortenLink/Scenes/LinksPopOver/Cell/ShortenLinkCellView.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewModel.swift
Labels: type : chore

#50 [#16] [UI] As a user, I can edit a shortened link
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Resources/Localize/en.lproj/Localizable.strings
  ShortenLink/Scenes/EditLink/EditLinkViewController.swift
  ShortenLink/Scenes/ShortenLink/ShortenLinkViewController.swift
  ShortenLink/Supports/Extensions/NSStackView+AddArrangedSubviews.swift
  ShortenLink/Views/DisableToggleableTextField.swift
Labels: type : feature

#53 [#17] [Integrate] As a user, I can edit a shortened link
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink/Application/AppDelegate.swift
  ShortenLink/Application/Base.lproj/Main.storyboard
  ShortenLink/Domain/Entities/EditingShortLink.swift
  ShortenLink/Domain/Factories/DependencyFactory+ViewModelFactoryProtocol.swift
  ShortenLink/Factories/Presentation/ViewModelFactoryProtocol.swift
  ShortenLink/Scenes/EditLink/EditLinkViewController.swift
  ShortenLink/Scenes/EditLink/EditLinkViewModel.swift
  ShortenLink/Scenes/Home/ViewController.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewController.swift
  ShortenLink/Scenes/LinksPopOver/LinksPopOverViewModel.swift
  ShortenLink/Scenes/ShortenLink/ShortenLinkViewModel.swift
  ShortenLink/Supports/Extensions/Foundation/Optional+Default.swift
Labels: type : feature

#55 [#54] Change app's bundle id
  ShortenLink.xcodeproj/project.pbxproj
  ShortenLink.xcodeproj/xcshareddata/xcschemes/ShortenLink.xcscheme
Labels: type : chore
